### ISSUE TITLE
Genesis addon/runtime support

### ISSUE THREAD

**Issue by lnguyen** [starkandwayne/genesis#102]

**Comment by dennisjbell** [comment]
Description would be super useful in what this is meant to accomplish...

**Comment by lnguyen** [comment]
Sorry was placeholder so I don't forget to have discussion about it. 
https://share.polymail.io/v1/z/b/NTgzNzM5ODFlMWMw/tufxMGGxOXRYQQpoDf2Q7ymquLB-7pfdlWgCKBzbR61OukCv3mvO8plKOpItWPKFuBIfXR-NmS3WRw92laud3HlDlf89JswnS72sPhI-_bPumsntA4EDKikFuiJIElQWG7L9tg5Wbwvj9v8WcAWuuq9J_ngOtlr02oyhqD94ohf-qLBEb1eVGkswI6Jz7HUIi4ckrZCsASdyLHLj2Y092OAsMArRtVHWyg6VUC3Kc9yAqvpic3abz9CHU9SUBJ4xjHb-NgTEHPXq-ScB1ETEmRTAc2uwATfgRlV8CXMf2bzobWg1RXtAT-WYwoCbEg==
 for reference

On Thu, Nov 24, 2016 at 1:04 PM "Dennis J. Bell"

<
mailto:
> wrote:

<![CDATA[a, pre, code, a:link, body { word-wrap: break-word !important; }]]>

Description would be super useful in what this is meant to accomplish...

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/starkandwayne/genesis/issues/102#issuecomment-262826632
, or

**Comment by geofffranks** [comment]
Seems like this should be managed similarly to cloud config?

**Comment by geofffranks** [comment]
Closing - obviated by genesis-v2

**Comment by geofffranks** [comment]
(genesis-v2 makes use of cloud-config + runtime-config)
