### ISSUE TITLE
1.6 release?

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#104]
I've been using head for a few weeks now and have not run into anymore bugs. I think we are good to go.

**Comment by jhunt** [comment]
Do the more recent bug fixes have release notes?

**Comment by bodymindarts** [comment]
Fixes I've been involved in are all documented :-)

**Comment by jhunt** [comment]
Great.  What about the other fixes?

**Comment by jhunt** [comment]
Done
