### ISSUE TITLE
When deploying bosh for the first time in a pipeline the 'wait for tasks' feature prohibits deployment

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#125]
Recently a task was added to not redeploy BOSH when the BOSH that is being redeployed has running tasks. When we want to deploy a fresh BOSH however this prohibits the deployment because the pipeline cannot connect to a BOSH that doesn't exist yet to check if it has tasks running.

**Comment by geofffranks** [comment]
Closing - obviated by genesis-v2 (using locker + locks inside concourse)
