### ISSUE TITLE
Support generating / injecting http basic auth passwords

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#139]
eg using:
```
$ htpasswd -c admin admin
New password:
Re-type new password:
Adding password for user admin
$ cat admin
admin:$apr1$e6vdL23T$iB9YFJxmgbOiRr19ErAPh/
```
If this is already supported.

**Comment by jhunt** [comment]
You should be able to use the `crypt-sha512` format for this.  The following works in my nginx basic auth setup:

```
$ safe gen secret/apache:password
$ safe fmt crypt-sha512 secret/apache password htpasswd
$ safe read secret/apache
--- # secret/apache
htpasswd: $6$cGIMBYcHCBagJNwS$Yism9zTYjWlahAyWRANOlZvt0T1JZmFC8nZAz.Lcb0klCLFLWKxCGZfL2wvsomBq8fsRdaV6erBWv.Y8VYngi0
password: VFdHKhwGq3kPNRipjOmyT5widpXsYEyiQhfYvPoxKc97hlkuJeBj0frOADJ2Jc77
```

Reviewing the [AUTHORING-KITS](https://github.com/starkandwayne/genesis/blob/master/docs/AUTHORING-KITS.md) doc, however, I don't see any information concerning secret formatting, but the code [here in bin/genesis](https://github.com/starkandwayne/genesis/blob/11c57e6cfac6e77fbe5783918a5e84ef9563fef4/bin/genesis#L663) shows what needs to be done:

```
password: random fmt crypt-sha512 at htpasswd
```

Perhaps we ought to add a note about using `format <x> [at <y>]`

**Comment by bodymindarts** [comment]
okay I will try this

**Comment by bodymindarts** [comment]
closed in favor of https://github.com/starkandwayne/safe/issues/96
