### ISSUE TITLE
Don't regenerate certs on `genesis secrets`

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#140]
When updating a distributed system like consul switching out the certs will cause the cluster to loose consensus.

**Comment by jhunt** [comment]
Can we just mark the certificates as fixed in Genesis Kits that utilize consul?

**Comment by bodymindarts** [comment]
Just retested this with consul, and it seems not to be an issue anymore. Don't know why I observed this failing... must have been another config change that triggered consul to behave strangely.
