### ISSUE TITLE
Ability to add custom helper scripts to kit that genesis will install

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#143]
My use case is I'd like to add provide some simple admin scripts to the hashistack-gensis-kit for unsealing / rekeying vault (for example). I'd like to commit these to the kit repo and have genesis install them under `./bin` in the resulting deployments repo.

I already had a discussion with @geofffranks about this and would welcome additional comments.

**Comment by geofffranks** [comment]
What if these scripts were just bundled in the kit, or in a directory in `dev`, and there was a `genesis` command to run them? Could make managing versions of the helper scripts easier, since they stay embedded in the kit itself, and you could run the right version of the script based on the version of the kit used for the target environment. Though it would make it a little more cumbersome for the end-user to run

**Comment by jhunt** [comment]
We could adopt the convention of other multi-call binaries like `git`, and if you run `genesis xyzzy`, it looks for a script/binary called `genesis-xyzzy` (note the hyphen) and just execs that with some env vars set (where is the root, what kit version, etc.)

Then you could pop a `genesis-vault` command inside the kit, and have it support subcommands like `rekey` and `unseal`, i.e.:

```
genesis vault rekey --threshold 2 --keys 4
genesis vault unseal
genesis vault seal
```

Thoughts?

**Comment by geofffranks** [comment]
👍

**Comment by bodymindarts** [comment]
I like it!

**Comment by drnic** [comment]
Examples for the bosh kit might be to run `bosh2 alias-env` and `bosh log-in`

**Comment by dennisjbell** [comment]
Would this be limited to scripts, or would we need to support packaged binaries, and if so, how to support different distributions?  My preference would be distribution-agnostic scripts (bash, cpan-less perl, anything that comes as part of all major Linux/BSD distros), but I want to make sure we're not coding ourselves into a corner.

**Comment by dennisjbell** [comment]
One issue with this is that kits are versioned, and each environment doesn't necessarily use the same version.  So to work around this, we'd have to either specify the version of the kit, or specify the environment file.

Examples:
```
genesis -k ["dev"|name[/version]] run <script> [<script options...>]
genesis -e <env> run <script> ...
```

Maybe with out -k or -e would use the latest (or dev if present).  Conversely, should these scripts be limited to only things that would target a specific environment, and as such, necessitate that environment being specified?

**Comment by geofffranks** [comment]
I'm comfortable making the environment a required parameter to this, so that the correct kit version can be determined + pass  data into the script, a la `genesis -e boshlite vault rekey`

**Comment by dennisjbell** [comment]
I would also like to suggest a "hand-off" subcommand, such as "run", "exec", "do" so that we don't limit what the script is, or add a genesis subcommand in the future that was already a script in a kit.

**Comment by geofffranks** [comment]
If we go that way, `genesis exec <boshlite[.yml]> vault rekey`?

**Comment by rkoster** [comment]
I'm a bit late to the party, but love this proposal. I would allow for reimplementing bucc as a genesis kit. Potential candidates to port would be `bucc {bosh,credhub,fly,uaac}` which all just lookup credentials and login.

**Comment by jhunt** [comment]
Handled in #258, and will be available as `genesis do <env> script [args ...]` in v2.6
