### ISSUE TITLE
"Failed to commit initial Genesis repository in bosh-deployments"

### ISSUE THREAD

**Issue by drnic** [starkandwayne/genesis#144]
I'm on an ubuntu vm and `genesis init --kit bosh` is failing as below. Ideas for debugging to figure out what's wrong?
```
$ uname -a
Linux bosh-bastion 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ git version
git version 1.9.1
$ perl -v
...
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi


$ genesis init --kit bosh
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "en_AU.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Downloading Genesis kit bosh (latest version)

Failed to commit initial Genesis repository in bosh-deployments/
```

But the `bosh-deployments` folder does look like a git repo; just a bad one:

```
drnic@bosh-bastion:~/deployments/bosh-deployments$ ll
total 20
drwxrwxr-x 4 drnic drnic 4096 Jul 14 09:27 ./
drwxrwxr-x 4 drnic drnic 4096 Jul 14 09:27 ../
drwxrwxr-x 4 drnic drnic 4096 Jul 14 09:27 .genesis/
drwxrwxr-x 7 drnic drnic 4096 Jul 14 09:27 .git/
-rw-rw-r-- 1 drnic drnic 3476 Jul 14 09:27 README.md
drnic@bosh-bastion:~/deployments/bosh-deployments$ git log
fatal: bad default revision 'HEAD'
```

**Comment by geofffranks** [comment]
If you go into that directory, and manually `git commit -m "initial commit"`, what happens? The error is being thrown because the git commit is failing. 

Alternatively, run the same `genesis init` command with `DEBUG=true` set.

As for the locale stuff, those appear to unrelated butl annoying warnings that we should look into

**Comment by jhunt** [comment]
As for the locale stuff, it would seem that en_AU is not a real language.

What does `locale -a` show you?

**Comment by drnic** [comment]
Discovered issue - on a new bastion I didn't have some git config setup.

```
git config --global user.name foo
git config --global user.email foo@bar.com
```

Perhaps we add a fail-fast if `git config user.name` or `git config user.email` are missing.
