### ISSUE TITLE
New user question: what is a Proto-BOSH?

### ISSUE THREAD

**Issue by drnic** [starkandwayne/genesis#145]
```
Is this a Proto-BOSH?

   1) Yes
   2) No, this bosh will be deployed by another BOSH
```

As a new user to genesis2 and a 5-year user of BOSH, I was left wondering "what is a Proto-BOSH" and "I don't think I want a Proto-BOSH, whatever it is", though `2)` is also what I don't want.

I think historically the `bosh create-env`/`bosh-init deploy`/`bosh micro deploy` BOSH is called a "Micro BOSH"?

**Comment by geofffranks** [comment]
Does the readme at https://github.com/genesis-community/bosh-genesis-kit answer this? 

Would welcome any verbiage changes on that kit that would help make things more approachable

**Comment by drnic** [comment]
Perhaps the outcome of `bosh create-env` is just a "BOSH", without a special name. Its really the only BOSH deployment method for most ppl.

Therefore perhaps what we need instead is a name for a BOSH deployed by a BOSH? Or we remove the prompt; and only support bosh-as-a-bosh-deployment via a flag for ppl who really really want to deploy bosh this way?
