### ISSUE TITLE
As an kit author I would like to be able to use opsfiles when authoring kits

### ISSUE THREAD

**Issue by rkoster** [starkandwayne/genesis#146]
This should be feasible now that `spruce` [supports](https://github.com/geofffranks/spruce/releases/tag/v1.11.0) the `--go-patch` flag.

**Comment by rkoster** [comment]
this would allow basing genesis kits on *-deployment repo's

**Comment by bodymindarts** [comment]
What do you mean with `on top of`?

Are you suggesting we copy the existing *-deployment opsfiles into subkits and release them as part of the kit?
Or do you intend to include some kind of reference to the upstream repo?

**Comment by rkoster** [comment]
reusing upstream templates

**Comment by jhunt** [comment]
Is this not possible today, because of spruce's support for `--go-patch`?

**Comment by rkoster** [comment]
yhea got it working locally by adding `--go-patch` [here](https://github.com/starkandwayne/genesis/blob/master/bin/genesis#L981) but don't know if this would break non go-patch based kits.

**Comment by jhunt** [comment]
It shouldn't.  The flag was added to spruce as an opt-in so that error messaging would remain consistent and understandable to people who have never even heard of go-patch.

I'm not even sure this is something that needs to be opt-in by the kit author; I think we can just add the `--go-patch` flag for all kit merges and we're good to go.  @geofffranks thoughts?

**Comment by geofffranks** [comment]
Yeah, I was just going to add it as a flag to the spruce merge function for all things

**Comment by rkoster** [comment]
nice! when will it be released?

**Comment by geofffranks** [comment]
Haven't done it yet, was focusing on templates for CF, but probably the next few days, unless you want to PR it sooner

**Comment by jhunt** [comment]
Don't forget to bump the min required version of spruce 😄

**Comment by rkoster** [comment]
@jhunt where is the min required version of spruce defined?

**Comment by jhunt** [comment]
Details in #147 review

**Comment by bodymindarts** [comment]
Does this mean compiled kits are no longer self container because they would reference files in external repositories?

If to that would mean we cannot use kits in offline environments.

**Comment by dennisjbell** [comment]
From the changes seen, I think it just means that the yaml files can be a
mix of regular spruce merge files and go-patch files, but all the files
still need to be located in the kit directory structure.

**Comment by rkoster** [comment]
what @dennisjbell said, this way we can submodule or subrepo `*-deployment` repo's and directly use their ops-files.

**Comment by bodymindarts** [comment]
So on compile-kit the entire submodule will be included in the kit tarball?

**Comment by geofffranks** [comment]
Or just use a pipeline to watch for upstream releases, copy in the relevant templates/ops files, and run through tests?

**Comment by rkoster** [comment]
Is there something like a `.kitignore` file, to ignore some files when compiling the kit?
