### ISSUE TITLE
"Vault [is] most easily deployed with Vault kit" which itself requires Vault

### ISSUE THREAD

**Issue by drnic** [starkandwayne/genesis#148]
The Genesis README includes:

> Genesis v2 makes use of Vault as a back-end for storing credentials, most easily deployed + managed via the [Vault kit](https://github.com/genesis-community/vault-genesis-kit), and the [safe CLI](https://github.com/starkandwayne/safe).

Except that Genesis requires Vault, even for deploying Vault itself.

```
$ genesis init --kit vault
$ cd vault-deployments
$ genesis new local
...
No Vaults have been targeted yet.

You will need to target a Vault manually first.
```

What are other ppl doing to bootstrap Vault here?

**Comment by jhunt** [comment]
if you are deploying your first vault,

```
$ vault server -dev
```

and then target it over localhost:8200.

this may be helpful: https://github.com/starkandwayne/codex/blob/master/aws.md#vault-init

**Comment by drnic** [comment]
Thanks for link.

**Comment by alvaropinot** [comment]
I've just run into this egg/chicken problem for a while with a brand new setup 😅. You guys just probably have a bunch of Vault instances around, making this scenario not a common one for you anymore 😉. Looks like spinning a local Vault dev is the way to go. Are there some tips somewhere in the `genesis` docs regarding the *start from scratch* state? If there is none, I think it's definitely worth adding a line closer to the *genesis* docs.

@jhunt Looks like the link above is dead as `aws.md` is now living inside `docs`. This one should be working https://github.com/starkandwayne/codex/blob/master/docs/aws.md#vault-init :) 

---

**Extra tip** 😜 for anyone that faces the *dead link* issue, in case it helps. Pressing **"Y"** to get a permalink whenever I'm linking in an issue/PR a file that might change later. Here the permalink for `aws.md` https://github.com/starkandwayne/codex/blob/560e1e8cbd2e7e4b95422ab2c06843bb556f6674/docs/aws.md#vault-init 
The CON about permalinks is that they point to that version of the file though.

Here a link to the github docs for the later feature https://help.github.com/articles/getting-permanent-links-to-files/

**Comment by jhunt** [comment]
We now also have `safe local`
