### ISSUE TITLE
Genesis should not bail when encountering dev versions of supporting utilities.

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#154]
While #150/#152 fixes the abiguous error message, the behaviour is still at odds with the way genesis v1 behaved.  In v1, if you were using a dev version, it would warn you, but allow you to continue.  I think that behaviour is necessary in order to vet new versions of supporting utilities.

**Comment by geofffranks** [comment]
The GENESIS_DEV_MODE env var can be set to force using dev-binaries.

**Comment by dennisjbell** [comment]
In that case, the test for development build is lacking:
```
		unless(envset('GENESIS_DEV_MODE') && $version =~ /development build/) {
```

Spruce did not report `development build`, it reported `(development)`

**Comment by geofffranks** [comment]
Fixed on master
