### ISSUE TITLE
CI Pipeline Should Support Smoke Tests

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/genesis#16]
The CI pipeline as generated currently does not attempt to run any sort of smoke tests against the BOSH deployments being automated.  This makes it difficult to auto-propagate to production environments safely.  Just because it deployed doesn't mean it works.

Introduce some way of specifying smoke tests to run on a per-global / per-site / per-environment manner.

Probably just a smoke-tests script in the env / site / global directory?

**Comment by bodymindarts** [comment]
In your suggestion would the smoke-tests script be a bash script that is executed in the concourse worker?
Alternatively how about being able to specify bosh errands as smoke tests?

**Comment by jhunt** [comment]
+1 @bodymindarts

The smoke tests should be errands, and we just need ci configure for the name of the errand to run.

**Comment by bodymindarts** [comment]
can be closed when latest code gets released
