### ISSUE TITLE
Genesis v1 repo projects that use .genesis_deps do not work with latest version

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#163]
The latest genesis v1 that is embedded in genesis v2 does not handle .genesis_deps file correctly.  First off, the new "v1.x.x" version string of the embed genesis is not recognized.  Secondly, and this may be due to a different, pre-existing issue, it is not correctly determining other versions:

```
This Genesis deployment requires safe version 0.0.14, but the current version could not be parsed
```

The safe version installed was 0.2.2

**Comment by norman-abramovitz** [comment]
I am not sure if this will help or not but I wrote up a bash semver script.

https://github.com/starkandwayne/bash-shell-utilities
