### ISSUE TITLE
When failing on missing/erroneous subkits, list *all*, not just first, before bailing

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#172]
Currently, genesis deploy will fail when it encounters the first erroneous subkit, which in the case of multiple bad subkits, requires multiple CI runs to detect them all.  Much more efficient to list all bad subkits in a single pass.

**Comment by jhunt** [comment]
This should go away with the blueprint stuff, right?

**Comment by dennisjbell** [comment]
It will depend on the author of the blueprint script, but yeah, the facilities will be there to make it possible to error with a complete message.

**Comment by jhunt** [comment]
I'm going to close this then.
