### ISSUE TITLE
Allow kits to specify a minimum previous kit version (or release versions)

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#179]
To improve upgrade paths via kits, we need to ensure that the kit/deployment that you're upgrading from is new enough to make the deployment successful.  Recent example is that Concourse 3.6 needs you to go through the painful upgrade path of 3.5 before it will work.  The kit that supports 3.6 should ensure first you're running 3.5 (or nothing for a fresh install obviously), but we can't do that right now because kits don't support prerequisites of existing deployments.

**Comment by jhunt** [comment]
We also can't do this because Genesis doesn't store the kit version anywhere to check against...

**Comment by jhunt** [comment]
See if we can set this metadata when we do it in #227

**Comment by dennisjbell** [comment]
Yes, the metadata will contain the kit-version and kit-name

**Comment by jhunt** [comment]
BEHOLD THE POWER OF CHECK HOOKS!

```
if have_exodus_data; then
    if [[ $(exodus kit_name) != "bosh" ]]; then
        echo "This does not appear to have been a BOSH deployment before today??"
        exit 2
    else
        v=$(exodus kit_version)
        if ! new_enough $v 0.3.0; then
            echo "please upgrade to 0.3.0 of the BOSH kit first!"
            echo "(you are only on $(exodus kit_version))"
            exit 2
        else
            echo "$v is new enough! (0.3.0 required)"
        fi
    fi
else
    echo "assuming this is a new deploy..."
fi
```
