### ISSUE TITLE
genesis requires hooks directory to be able to compile kit

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/genesis#181]
when there is no hooks dir, it complains
```
/Users/xiujiao/work/sw/concourse-genesis-kit does not look like a valid kit directory:
  * /Users/xiujiao/work/sw/concourse-genesis-kit/hooks directory does not exist

Cannot continue.
```
I pass by this by adding an empty hooks/ for now since I have to cut a prerelease for comcast

**Comment by thomasmmitchell** [comment]
Yup. Aware of this. This issue was previously filed with the @dennisjbell issue-tracking system, where I just yell at him about it in Slack.

**Comment by thomasmmitchell** [comment]
With results like that, hes the best issue-tracking system there is
