### ISSUE TITLE
Re-Prompt for ssh key selection if did not find existing key in safe

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/genesis#189]
For git-ssh deployment key, you will be asked 
```
"Use existing key in Vault","Add an existing key in Vault", "Generate a new key"
```
when you select to use existing key, but later did not find the key in the safe path, it should re-prompt you with the questions to let you reselect

```
"Use existing key in Vault","Add an existing key in Vault", "Generate a new key"
```

**Comment by jhunt** [comment]
This was for the CI wizard, which is now gone.  RIP the CI Wizard, he just couldn't cast that saving spell...
