### ISSUE TITLE
Genesis Should Use credhub on BOSH

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/genesis#193]

**Comment by norman-abramovitz** [comment]
If I understand correctly, Genesis uses Safe to access Vault.   If we want to support Credhub, does that mean we modify Safe to provide the Credhub interface?

**Comment by jhunt** [comment]
Genesis uses safe to set secrets in the Vault.  Most of those secrets (certs especially) are not used by operators, and clutter up the Vault.  Additionally, Kits are currently overriding BOSH v2 `((variable))` calls to Spruce `(( vault ... ))` calls, and we'd like to stop doing that for everything except the things we care about.

Getting `safe` to support credhub is a good goal, but not necessary for the first phase of rolling this out.  We need to get credhub and credhub-cli working with Genesis to roll this change.

**Comment by jhunt** [comment]
This is pretty much already supported.  Putting credentials we don't care about in Credhub means that we can cut down on the noise in Vault, and only the important bits are there.  Luckily, it didn't require any changes from Genesis itself; only the kits had to move to supporting Credhub and using it.

The BOSH kit, as of the next (modernized) release, comes with Credhub built-in.  This has been verified in both vSphere and AWS environments.  See https://github.com/genesis-community/bosh-genesis-kit/pull/26.

The Vault Kit, in https://github.com/genesis-community/vault-genesis-kit/pull/9, now uses that Credhub to gen-and-store its Consul peer cert.
