### ISSUE TITLE
How to easily update policy to pipeline when it has new credentials need to access

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/genesis#202]
We set up pipeline for cf deployment without shield agent using `genesis ci`.
A vault policy is generated by `genesis ci` and associated with the role id.

Later on, we added shield agent for cf, now we have shield related credentials that cf pipeline needs to access, while it is not in the policy genesis set earlier

We can run `genesis vault-policy` to get the updated policy into a file, then `safe vault update sys/policy/policy_name policy_file_name` to update policy.

It will be nice we can run something like `genesis policy-update` to automatically update the policy when there are credentials paths added or removed.

**Comment by jhunt** [comment]
The correct way to handle this, as @dennisjbell and I have come to understand, is to remove the vault-policies apparatus in its entirety.

**Comment by jhunt** [comment]
This has been removed in 2.6
