### ISSUE TITLE
`genesis -T` (set type) does not work in conjunction with `--template`

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/genesis#21]
Tried `genesis new deployment -t bosh-init --template bosh my-deployment-name` today, and instead of making it a bosh-init deployment, it made it a regular deployment, though it did pull the templates properly. The `-t` flag should still set the deployment type on the new deployment repo. If any type was provided via upstream templates, `-t` should override that.

**Comment by jhunt** [comment]
Was the upstream template a bosh-init template or a normal template?

**Comment by geofffranks** [comment]
It was a normal template

**Comment by geofffranks** [comment]
Closing in favor of #24, #25, #26
