### ISSUE TITLE
More stringent handling of filename creation

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/genesis#217]
For example, `genesis deploy lab20.yml` creates a manifest called `lab20.yml.yml`. Which is redundant. We need more stringe.

**Comment by dennisjbell** [comment]
that is at odd with the code:

https://github.com/starkandwayne/genesis/blob/master/bin/genesis#L1517-L1524 :

	$env =~ s/.yml$//;
	$deployment_prefix ||= $env;
	my $deployment = "$deployment_prefix-" . deployment_suffix;

	mkdir_or_fail(".genesis/manifests");

	$ENV{REDACT} = 'true';
	mkfile_or_fail(".genesis/manifests/$env.yml", merge_manifest($env, $merge_opts));

The first highlighted line strips .yml off the end of `$env`, and the last line uses it as the file location.    Which version of genesis are you using, and are you referring to the .genesis/manifest/<env>.yml file, or another location?

**Comment by thomasmmitchell** [comment]
I definitely had the file, but I can't... reproduce it now. we can chalk it up to an artifact from an earlier version that had never been noticed. I'll reopen if I can rediscover it.

**Comment by jhunt** [comment]
😢 
I really wanted to see a commit titled "More Stringe"
