### ISSUE TITLE
Genesis does not recognize Vault's changed version string

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/genesis#218]
Vault version 0.9.3

genesis init --kit bosh-init
Unrecognized version string 'Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')' for vault

**Comment by dennisjbell** [comment]
Odd that it does recognize it for 0.9.1:
Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1')

I'll look into this.

**Comment by norman-abramovitz** [comment]
Could be me since I am flying blind on figuring out how to use Genesis.

**Comment by jhunt** [comment]
What version of Genesis are you using, @norman-abramovitz ?

**Comment by norman-abramovitz** [comment]
Genesis v2.4.1
