### ISSUE TITLE
Support `list` (multi-line) and `blocks` (multi-blocks) in prompt_for

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/genesis#256]

**Comment by dennisjbell** [comment]
I explicitly chose not to call multi-line "list" because it was confusing what was a list and what wasn't.  I could support "lines" however in the same style as you have proposed "blocks"

**Comment by jhunt** [comment]
The main reason I kept typing `list` in the hook scripts is because it's a _list_ of DNS servers (jumpbox openvpn feature), a _list_ of CF spaces (concourse cf/uaa auth feature), a _list_ of data stores (BOSH vSphere IAAS feature), etc.

My issue with "lines" (and indeed, "multi-line") is that a "block" is a multi-line string, or "lines" in that it is composed of several lines all terminated with the newline character.
