### ISSUE TITLE
New hooks helper: `bosh_cpi`

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/genesis#259]
Write a new helper, called `bosh_cpi()` that effectively runs this:

```
bosh -e "$director" env --json | jq -r '.Tables[0].Rows[0].cpi
```
Using the correct value for `$director`

Turns out Azure is kind of a PITA and requires special handling.  I've done this now manually in two kits to handle the availability sets / availability zones problem.  Let's make it less kit-specific.

**Comment by dennisjbell** [comment]
👍
