### ISSUE TITLE
genesis can not recognize hook 'params'

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/genesis#266]
The jumpbox-genesis-kit has `hook/params`file, when we run `genesis new` for jumpbox, it complains `Unrecognized hook 'params'.

We should convert jumpbox kit to `modern: new and blueprint` style 

From James:

^ ^ we will be removing params support
it was a tortured thing, that hook

**Comment by xiujiao** [comment]
LOL.
From XJ: 
> backwards compat sounds good to me

Also, from XJ:
> What James said in Update

**Comment by dennisjbell** [comment]
Fixed in refactor branch
