### ISSUE TITLE
Hooks that use internal case statements problematic

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#269]
While using an internal case statement seems elegant, it is problematic from a hooks perspective because genesis can't determine if the kit hooks supports the different cases.  For example, you may have a check script that support checking `cloud-config` but not `parameters`, there is no way to tell this from genesis, and if in the future we add a further check type, old kits that don't support it can't be detected and degrade gracefully.

Instead, we should have check-cloud-config and check-parameters hooks.  Similarly, we could have check-secrets, add-secrets, and rotate-secrets hooks.  (This would also forever solve the does check secrets go in checks or secrets debate :D )

**Comment by dennisjbell** [comment]
Exception to this would be the addon hook, which is solely owned by the kit and thus can act on its arguments however it sees fit.

**Comment by jhunt** [comment]
Proposed solution:

We define a single hook, called `check`, that is responsible for the following:

1. Validating environment parameters
2. Validating that secrets exist and are usable (IP SANs, key strength, CA-Cert agreement, etc.)
3. Validating cloud-config, if present

We modify the `secret` hook to operate with a `GENESIS_HOOK_MODE` variable that gets set to one of the following variables:

1. **new** - `genesis new` needs to flush and recreate all credentials, even fixed ones
2. **update** - Add all the missing secrets, in no-clobber mode.  If certificates have expired, the kit is free to renew or re-issue them to keep things running.
3. **rotate** - Rotate all credentials, whatever that means to the kit.  Ex: the BOSH kit may re-issue the NATS client / server certificates, and re-issue the CA certificate.

**Comment by dennisjbell** [comment]
Fixed in refactor branch
