### ISSUE TITLE
bosh() helper for hooks

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/genesis#272]
We have an environment variable called `GENESIS_BOSH_COMMAND`, but that's annoying.

Can we have a `bosh` function that just runs that for us, with proper argument quoting?

i.e.
```
bosh() { $GENESIS_BOSH_COMMAND "$@"; return $? }
```

**Comment by dennisjbell** [comment]
Also adding on for `genesis()` instead of `$GENESIS_CALLBACK_BIN` for same reason
