### ISSUE TITLE
`genesis embed` copies wrong file

### ISSUE THREAD

**Issue by Proplex** [starkandwayne/genesis#294]
Currently, running `genesis embed` copies the existing Genesis runtime to `$pwd/.genesis/bin/genesis`. Because it is only the Genesis script itself, and none of the libraries, using `$pwd/.genesis/bin/genesis` will fail with 
```
Can't locate Genesis.pm in @INC (you may need to install the Genesis module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at sb-changes/.genesis/bin/genesis line 23.
BEGIN failed--compilation aborted at sb-changes/.genesis/bin/genesis line 23.
```

A better method would be to copy the Genesis installation/inflation runtime (the file that can be downloaded via the GitHub releases). This way, when run, it installs the entire Geese runtime.

A temporary fix in the meantime would be to run `cp $(which genesis) ./.genesis/bin/genesis`, which embeds the Geese inflation script in the respective folder.

**Comment by jhunt** [comment]
I could have sworn we had an environment variable that we set in the stub, so that we could handle this very situation.  I'll check into it this morning.
