### ISSUE TITLE
Add edit_environment helper with built-in manual

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#324]
There is a growing trend for kits to allow the generated environment file to be edited prior to secrets generation or other actions.  I would like to capture this in a helper that opens a vim session split with a read-only copy of the manual on the right side, so that a) users know the options that they can change, b) users don't have to open the web or another shell to see the manual, and c) users learn that you can actually get the manual from genesis.

**Comment by jhunt** [comment]
What if I prefer emacs?

**Comment by dennisjbell** [comment]
While I know we can do this with vim, it would be great if we could support other editors for non-vimmers.  Just don't know which ones can support opening split files. To get out the door, $EDITOR can be inspected and if its vi|vim|*vim, we enable that feature, and otherwise, tough luck

**Comment by dennisjbell** [comment]
@jhunt I believe there's a 12-step program for that ;P

**Comment by dennisjbell** [comment]
for VI: `$EDITOR -O <env> <manual>`
for emacs: `$EDITOR -nw <env>  -f split-window-horizontally <manual> -f other-window`

**Comment by dennisjbell** [comment]
nano can open two files with `nano -F file1 file2` but cant support split screen

**Comment by jhunt** [comment]
can't vimmers just `<Esc>:!genesis man env`?
