### ISSUE TITLE
Make it clear that _deployment on template names is proper in the documentation or make it work correctly

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/genesis#34]
The following command prompted me for github username/password.

genesis new deployment --template cf_deployment cf

The description below for the template parameter does not make it clear that the _deployment cannot be specified on the command line.   Either improve the documentation or allow _deployment to be written in the template parameter.  

The command that worked was

    genesis new deployment --template cf

The `NAME` parameter looks to be required in the help but actually it was optional if the --template parameter is specified.   

```
USAGE: genesis new deployment [options] NAME

  Create a new deployment, complete with all the correct templates in
  global/, and a base configuration.  This will create a sub-directory
  in the current working directory, named <NAME>-deployments, and set
  it up with git version control.

  OPTIONS

    -t, --template <name>

        Base the deployment off of an upstream Genesis template, by
        cloning a repository from github.com and using that.

        Templates can be specified as qualified name containing the
        Github org/user and repository name, i.e. "jhunt/bolo", or
        as a simple name, i.e. "shield", which will be inferred to
        belong to the starkandwayne organization.
```

**Comment by jhunt** [comment]
I just tested this locally:

```
$  ./bin/genesis new deployment --template cf-deployment
cloning from template https://github.com/starkandwayne/cf-deployment
Cloning into '/Users/jhunt/code/genesis/cf-deployments'...
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 129 (delta 0), reused 0 (delta 0), pack-reused 126
Receiving objects: 100% (129/129), 29.30 KiB | 0 bytes/s, done.
Resolving deltas: 100% (49/49), done.
Checking connectivity... done.

Embedding genesis script into repository
Treating 'development' version as up-to-date with 1.5
This genesis deployment requires the 'certstrap' command
```

Genesis properly removes the `-deployment` suffix and uses just `cf` for the template name, allowing it to properly clone the upstream template repo (`starkandwayne/cf-deployment`).  In your case, the problem was that you were specifying the template name as `cf_deployment` (note the incorrect use of an underscore in place of the hyphen)

As for the second sub-issue, I will go ahead and update the usage message to indicate that `NAME` is optional if the `--template` argument is given.
