### ISSUE TITLE
`genesis ci` documentation

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/genesis#39]
There should be more/better help and documentation about `genesis ci`, what it does, how the pipelines are built/configured/uploaded, what types of pipeline nodes (alpha,beta, etc) exist, and how they all interact

**Comment by jhunt** [comment]
We were waiting on `genesis help` and Makefile integration until we were comfortable with the structure and tooling around CI pipelines.  But this does definitely need done.

**Comment by geofffranks** [comment]
We now have docs for genesis ci.yml configuration + repipe
