### ISSUE TITLE
`network` not in `resource_pools` for BOSH lite

### ISSUE THREAD

**Issue by qanx** [starkandwayne/genesis#42]
`resource_pools.network` is a required field - the network name should be `cf`

Doc:
https://bosh.io/docs/deployment-manifest.html#resource-pools

**Comment by geofffranks** [comment]
Fixed in https://github.com/starkandwayne/cf-deployment/commit/537c8c2081058922d4e7d04320213f5249ed8f4b

All other existing genesis template repos have the network property set in resource-pools.yml for bosh-lite
