### ISSUE TITLE
Dedicated image for genesis pipelines

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#43]
I propose curating a starkandwayne/genesis image for the pipelines genesis creates. I don't see the benefits of reusing starkandwayne/concourse.
AFAIK starkandwayne/concourse is being used across multiple projects of different kinds and is changing for reasons independent of the needs of genesis. There may be some merit in de-duplicating images across similar looking projects but since genesis is a very focused tool I would prefer having all resources it depends on as isolated / explicit as possible.

**Comment by jhunt** [comment]
What does Genesis need above and beyond the concourse image?

**Comment by bodymindarts** [comment]
I assume starkandwayne/concourse contains a lot that genesis doesn't require.

**Comment by bodymindarts** [comment]
I can't even find where the Dockerfile for starkandwayne/concourse lives. What repo is it in?

**Comment by longnguyen11288** [comment]
https://github.com/starkandwayne/dockerfiles

**Comment by bodymindarts** [comment]
Running the pipeline that got 
```
Authenticating to Vault at https://10.58.111.42:8200
`vault' command not found in your $PATH
  (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
You may need to install Vault in your task image
```

So there you have it. A thing that no client depended on yet.

**Comment by jhunt** [comment]
Can you give this another shot?  I think vault is in there somewhere...

**Comment by bodymindarts** [comment]
That image is being over complected imo.
