### ISSUE TITLE
bugs when trying to run genesis pipeline

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#45]
These are things I have run into and changed locally while trying to get the genesis pipeline working. This issue is a reminder to create a PR with the changes

- `CI_VAULT_APP_ID` is not being set (`VAULT_APP_ID` is)
- use `curl -k` when authenticating to vault from pipeline
- export VAULT_TOKEN before `vault secret/handshake`

**Comment by geofffranks** [comment]
Additionally, it seems like the examples of APP_ID and USER_ID configs set in the pipeline.yml are backwards compared to the defaults that the script sets while talking to vault

**Comment by geofffranks** [comment]
`curl -k` should probably only be used when `VAULT_SKIP_VERIFY` is set in the environment.

For troubleshooting failures of the curl to auth, we should re-run the curl in verbose mode, to see what curl/vault didn't like, since the errors aren't getting properly output when `curl -s` is used.

**Comment by jhunt** [comment]
FYI: Genesis CI pipelines have only been tested on non-credential'd deployments (mostly, a shell deployment we used for testing)

**Comment by geofffranks** [comment]
Yeah, we're just documenting the things that need fixing to get them to work on credentialed deployments, so we can make sure to include in a single PR.
