### ISSUE TITLE
Upload new stemcells to bosh in ci pipeline

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#51]
Currently when `site/stemcell/*` changes the deployment will fail and it is necessary to manually upload the bosh stemcell.

**Comment by bodymindarts** [comment]
More precise scenario description:

- new site with a new bosh
- pipeline is set via `genesis ci repipe`
- job to deploy to the new site is run
- job errors because `stemcell doesn't exist`

Example [here](https://ci.vsphere.starkandwayne.com/pipelines/dingo-postgresql-deployments/jobs/aws-staging/builds/2)

**Comment by jhunt** [comment]
How did you set up the files under `site/stemcell/`?

**Comment by bodymindarts** [comment]
`site/env/stemcell/{name,sha1,version}`

**Comment by bodymindarts** [comment]
Guess it needs `url`? Is there a `genesis add stemcell ...` that will use the index in the works?

**Comment by jhunt** [comment]
Try `genesis use stemcell <name> [<version>]`

Currently, a version of "latest" will cause genesis to track the index, which is most likely what you want.

**Comment by jhunt** [comment]
(and yes, I know, the documentation is lacking -- I want to make sure the CLI invocations "feel right" before comitting to them officially)

**Comment by bodymindarts** [comment]
Yup `genesis use stemcell <name>` worked.
