### ISSUE TITLE
Genesis should check that spruce version is up to date

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#66]
Got sidelined due to some weird errors regarding static IPs already allocated, but we couldn't find the issue when we traced the yml.

Turns out that this is a problem with using an older copy of spruce.  Genesis should verify that the version of spruce is up to date, not that it simply exists

**Comment by jhunt** [comment]
What version did you have, and what version did you need?

**Comment by geofffranks** [comment]
Isn't this covered by the dependency checking specified per deployment repo? Or is there an operator built into the template Genesis generates that requires a specific version of spruce?

**Comment by jhunt** [comment]
I agree with @dennisjbell that a baseline version of Spruce, without any known major bugs, ought to be required by Genesis.

**Comment by geofffranks** [comment]
Closing - obviated by genesis-v2
