### ISSUE TITLE
Issues with syncing with genesis-index during cmd_build

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis#69]
Currently genesis contacts the index during cmd_build(). This has 2 negative effects:
- a lot of commands run cmd_build twice in a row (once redacted once un-redacted) and it is annoying to wait that long twice during the same command flow.
- in a pipeline things can get out of sync. eg when using `track` it is possible for a beta environment to deploy a later version of a release than the alpha environment because the version is resolved while building the manifest.

Suggestion:
Only resolve releases when deploying in alpha environment.
Only resolve stemcells in alpha and beta environment.
All other environments copy the data and don't attempt to resolve to index

**Comment by jhunt** [comment]
I believe the solution to this issue was to not use track with CI pipelines, and to provide a warning when doing so.
