### ISSUE TITLE
Docker image hard-codes genesis version

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/genesis#76]
We seem to trigger building a new version of the genesis docker image every time we ship genesis, but the genesis script included in the image is hard-coded to 1.5.2. Should this be updated to pull in the latest GH release genesis, and make use of that, so we can auto-trigger docker builds based off new genesis versions?

**Comment by bodymindarts** [comment]
Actually the [ship-it script](https://github.com/starkandwayne/genesis/blob/master/ci/scripts/shipit#L56) auto increments the version in the [Dockerfile](https://github.com/starkandwayne/genesis/blob/master/Dockerfile#L6) to keep the referenced version in sync.
