### ISSUE TITLE
make refresh --pretend

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/genesis#82]
Would like to show the difference between what is currently in .global and .site from the global and <site>/site dirs that would be applied when make refresh is run.  Currently this is doable by running make refresh, doing the git diff, then git checkout .global .site to backout those changes you don't want.

**Comment by jhunt** [comment]
Is it not sufficient to do the following?

```
diff -ur ../../global .global
diff -ur ../site .site
```

?

**Comment by geofffranks** [comment]
Closing - obviated by genesis-v2
