### ISSUE TITLE
Feature Request: "genesis update" 

### ISSUE THREAD

**Issue by kitsirota** [starkandwayne/genesis#86]
Please add the ability to upgrade genesis in place, via command.  Ideally something like genesis update would wget down the latest release, move the old version to .bak and drop in the latest version.

Huge kudos if we can get genesis to also update spruce and safe to the latest builds.

Thanks!

**Comment by johnlonganecker** [comment]
If you use a mac I highly recommend you use homebrew and checkout S&W's homebrew tap https://github.com/starkandwayne/homebrew-cf this may solve all your problems.

**Comment by kitsirota** [comment]
Thanks John!  Im mostly working out of ubuntu and windows these days.  We have a few dozen jumpboxes and its cumbersome to keep all of these running the latest versions of S&W tools.  We could could script this ourselves, but it would be nice if the genesis could support managing its own version.

**Comment by jhunt** [comment]
Are you guys not using https://github.com/starkandwayne/jumpbox?

**Comment by kitsirota** [comment]
Thanks James, I'll work that back into our update process.
