### ISSUE TITLE
Allow Local Caching of URLs

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/genesis#97]
Look for `/srv/releases/<name>-<verison>.tgz` and `/srv/stemcells/<name>-<version>.tgz` for locally cached copies of stemcells and releases, and use those (as `file:///` URLs) instead of the upstream URLs, if present.  SHA1 checksums should also be calculated using these files, if they exist.

A new environment variable, `GENESIS_LOCAL` should force Genesis to rely exclusively on these locally cached assets.

**Comment by bodymindarts** [comment]
To clarify:
Local files take precedent over remote urls and `GENESIS_LOCAL` drops remote urls entirely?

**Comment by geofffranks** [comment]
Closing - obviated by genesis-v2
